name: "Python Code Quality and Lint"
on: [pull_request]
jobs:
  PyLint:
    runs-on: ubuntu-latest
    steps:
      - name: "Clone Repo"
        uses: actions/checkout@v2
      - name: "Install dependencies"
        run: pip3 install -r requirements.txt ; pip3 install pylint
      - name: "Run Pylint"
        id: pylint
        run: |
          echo $(pylint job.py)
          echo "::set-output name=pylint_report::$(pylint job.py)"
      - uses: peter-evans/commit-comment@v1
        with:
          body: |
            Pylint report
            ${{steps.pylint.outputs.pylint_report}}
            