name: "Python Code Quality and Lint"
on: [pull_request]
jobs:
  PyLint:
    runs-on: ubuntu-latest
    steps:
      - name: "Clone Repo"
        uses: actions/checkout@v2
      - name: "Install dependencies"
        run: pip3 install -r requirements.txt
      - name: "Run Pylint"
        run: pylint job.py