name: "Python Code Quality and Lint"
on: [pull_request]
jobs:
  PyLint:
    runs-on: ubuntu-latest
    steps:
      - name: "Clone Repo"
        uses: actions/checkout@v2
      - name: "Install dependencies"
        run: pip3 install -r requirements.txt ; pip3 install pylint
      - name: "Run Pylint"
        run: |
          echo $(pylint job.py) > lint_results.txt
        id: pylint
      - uses: actions/upload-artifact@v1
        with:
          path: ./
          name: lint_results
      - uses: actions/download-artifact@v1
        with:
          name: lint_results
      - uses: machine-learning-apps/pr-comment@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: ./lint_results.txt
