name: "Python Code Quality and Lint"
on: [pull_request]
jobs:
  PyLint:
    runs-on: ubuntu-latest
    steps:
      - name: "Clone Repo"
        uses: actions/checkout@v2
      - name: "Install dependencies"
        run: pip3 install -r requirements.txt ; pip3 install pylint
      - name: "Run Pylint"
        id: pylint
        run: |
        delta=$(pylint job.py)
        echo "::set-output name=lint_report::$delta"

      - uses: mshick/add-pr-comment@v1
        with:
          message: |
            ${{ steps.pylint.outputs.lint_report }}
            🌏
            !
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]' # The user.login for temporary GitHub tokens
          allow-repeats: false # This is the default