name: "Python Code Quality and Lint"
on: [pull_request]
jobs:
  PyLint:
    runs-on: ubuntu-latest
    steps:
      - name: "Clone Repo"
        uses: actions/checkout@v2
      - name: "Install dependencies"
        run: pip3 install -r requirements.txt ; pip3 install pylint
      - name: "Run Pylint"
        id: pylint
        run: |
          echo $(pylint job.py)
          echo "::set-output name=pylint_report::$(pylint job.py)"
      - uses: mshick/add-pr-comment@v1
        with:
          message: |
            Pylint report
            steps.pylint.outputs.pylint_report
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]' # The user.login for temporary GitHub tokens
          allow-repeats: false # This is the default